---
title: "Helpful Resources"
output: html_document
---

<br>
<br>

### Introduction to R & GitHub

**Comprehensive R Resources**

* [OHI Data Science Training](http://ohi-science.org/data-science-training/index.html)  ---  an online book written by The Ocean Health Index Team as an introduction to data science with R, with a focus on the tools used for calculating the OHI.
* [R Cheatsheets](https://www.rstudio.com/resources/cheatsheets/)  ---  a collection of 8x11 pages (double-sided) each crammed with all-you-need-to-know information about a given package
* [R for Data Science (R4DS)](http://r4ds.had.co.nz/)  ---  classic book for learning to do data science with R
* [Why RMarkdown?](http://ohi-science.org/globalfellows/why_rmarkdown.html) --- OHI fellow article
* [Stat545](http://stat545.com/topics.html)  ---  a well-organized and comprehensive website for a statistics course at UBC, which teaches R/RStudio as well as Git/GitHub

**Overview of GitHub**

* [Why GitHub?](http://ohi-science.org/globalfellows/why_git.html) --- OHI fellow article
* [Happy Git and GitHub for the useR](http://happygitwithr.com/)  ---  classic book for integrating Git + GitHub with your R workflows

<br>

### Scientific Computing

**Parallel Processing** --- useful resources that go over `foreach` and `doParallel`, both used frequently in OHI workflow 

* [Parallel Computing in 5 Minutes](http://blog.aicry.com/r-parallel-computing-in-5-minutes/index.html)
* [Using Multiple Cores with `doParallel`](http://michael.hahsler.net/SMU/LearnROnYourOwn/code/doMC.html)
* [CRAN documentation](https://cran.r-project.org/web/packages/doParallel/vignettes/gettingstartedParallel.pdf)

<br>

### Shiny Dashboard

* [Setting It Up](http://docs.rstudio.com/shinyapps.io/index.html)
* [Shiny User Showcase](https://www.rstudio.com/products/shiny/shiny-user-showcase/)
* [Shiny RStudio Gallery](https://shiny.rstudio.com/gallery/)

**Example**

* [Example 1: New Zealand Tourism](https://mbienz.shinyapps.io/tourism_dashboard_prod/)
* [Example 1 Code](https://github.com/nz-mbie/tourism-dashboard-public)

<br>

### Website Customization

**GitHub Pages**

* [Example 1: OHI Baltic Health Index](https://github.com/OHI-Science/ohi-webapps_gh-pages2)
* [Example 2: RMarkdown-Rstudio Webpage](https://github.com/rstudio/rmarkdown/tree/gh-pages)

**Custom Formats**

* [Example 2: Tufte](http://rstudio.github.io/tufte/)
* [RMarkdown Custom Formats](https://blog.rstudio.com/2016/03/21/r-markdown-custom-formats/)

**Text-Image Wrapping**

* [Example 1](https://github.com/OHI-Science/ohi-webapps_gh-pages2/blob/gh-pages/about.Rmd)
* [Example 2](http://www.rci.rutgers.edu/~ag978/litdata/figs/)
* [Background Image in RMarkdown](https://robertmyles.github.io/2017/01/02/tips-and-tricks-for-r-markdown-html/)

<br>

### Data Visualization

**R colors and palettes**

* [R color cheatsheet](https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/colorPaletteCheatsheet.pdf)
* [Customizing colors in R](https://mgimond.github.io/ES218/Week04d.html)
* [Color palettes](http://www.di.fc.ul.pt/~jpn/r/GraphicalTools/colorPalette.html)

**ggplot2**

* [Complete tutorial](http://r-statistics.co/Complete-Ggplot2-Tutorial-Part1-With-R-Code.html#6.%20How%20to%20Change%20the%20X%20Axis%20Texts%20and%20Ticks%20Location)
* [Customizing axis tick marks and labels](http://www.sthda.com/english/wiki/ggplot2-axis-ticks-a-guide-to-customize-tick-marks-and-labels)
* [Changing colors automatically and manually](http://www.sthda.com/english/wiki/ggplot2-colors-how-to-change-colors-automatically-and-manually)
* [Exploring some themes](http://t-redactyl.io/blog/2015/12/creating-plots-in-r-using-ggplot2-part-1-line-plots.html)

**cowplot**

* [Introduction](https://cran.r-project.org/web/packages/cowplot/vignettes/introduction.html)


**ggrepel**

* [Examples](https://cran.r-project.org/web/packages/ggrepel/vignettes/ggrepel.html)






