---
output:
  pdf_document: 
    latex_engine: xelatex
header-includes:
- \usepackage[fontsize=16pt]{scrextend}
- \usepackage{fontspec}
classoption: landscape
geometry: "left=0.1cm,right=0.1cm,top=2cm,bottom=1cm"
---

\pagenumbering{gobble}

The amount of protection provided by marine and coastal habitats serving as natural buffers against incoming waves. Shoreline-protecting habitats include mangrove, saltmarsh, coastal sea ice, coral reefs, and seagrass.

\vspace{0.5in}

\noindent
$\begin{aligned}
& x_{cp} \text{   is the status of the coastal protection goal}\\
\\
& x_{cp} = \left(\sum^N_{k=1} (h_k \times w_k \times A_k) \right) \left(\sum^N_{k=w} (w_k \times A_k) \right)^{-1} \\
\\
& h = \frac{C_c}{C_r}\\
\\
& h \text{   is a measure of the habitat's condition with respect to its reference condition}\\
& C_c \text{  current health of shoreline-protecting habitat $k$ in a region}\\
& C_r \text{  is the reference condition of habitat $k$}\\
& w \text{  is the rank weight of the habitat's protective ability}\\
& A \text{   is the area within a region for each $k$ habitat type}
\end{aligned}$